import { cert, initializeApp } from 'firebase-admin/app';
import { DecodedIdToken, FirebaseAuthError, getAuth } from 'firebase-admin/auth';
import { ServerError } from '../lib/error';
import { Service } from './common';

export class AuthService implements Service {

  public async init(): Promise<void> {

    if ( ! process.env.FIREBASE_SERVICE_ACCOUNT )
      throw new Error('FIREBASE_SERVICE_ACCOUNT environment variable not set!');

    const serviceAccount: any = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT);

    // Fix new line issues
    serviceAccount.private_key = serviceAccount.private_key.replace(/\\n/g, '\n');

    initializeApp({
      credential: cert(serviceAccount)
    });

  }

  /**
   * Verifies an ID token generated by Firebase client SDK and returns the decoded object.
   * @param token Firebase client SDK ID token
   * @returns Decoded object
   */
  public async verifyToken(token: string): Promise<DecodedIdToken> {

    let decoded: DecodedIdToken;

    try {

      decoded = await getAuth().verifyIdToken(token);

    }
    catch (error) {
      console.error(error);
      throw new ServerError('invalid-request', (error as FirebaseAuthError).message);

    }
    
    return decoded;

  }

}